version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 10
    reviewers:
      - "fahim06"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "security"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci(actions)"
    labels:
      - "ci"
      - "dependencies"
